# Set language for the project
language: cpp

# Package dependencies
addons:
  homebrew:
    update: true
    packages:
      - bison
      - ftgl
      - ninja
      - create-dmg
      - jq

# Add updated Qt libs (serial build only)
before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" && "$PARALLEL" = "false" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" && "$PARALLEL" = "true" ]]; then brew install open-mpi; fi

# Build Stages
jobs:
  include:
    - os: osx
      osx_image: xcode9.4
      env:
        - FLAVOUR="HighSierra"
        - PARALLEL=false
    - os: osx
      osx_image: xcode11.3
      env:
        - FLAVOUR="Mojave"
        - PARALLEL=false

cache:
  directories:
    - artifacts

script:
  - VERSION=`grep "DISSOLVEVERSION" src/version.h | sed "s/.*\"\(.*\)\"/\1/g"`
  - SHORTHASH=`git rev-parse --short HEAD`
  - echo 'USECREATEDMG="TRUE"' >> ci/osx/dissolve-gui.dmginfo
  - ./ci/osx/build.serial.gui
  - echo "Flavour of build environment is: $FLAVOUR"
  - mv artifacts/Dissolve-GUI-${VERSION}.dmg artifacts/Dissolve-GUI-${VERSION}-${SHORTHASH}-${FLAVOUR}.dmg

deploy:
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
  script: ./ci/scripts/update-release -r ${TRAVIS_REPO_SLUG} -t continuous -n "Continuous Build (${TRAVIS_COMMIT})" -b "Continuous release from current \`develop\` branch at ${TRAVIS_COMMIT}. Built ${DATE}." -p artifacts/*dmg

# Branch Safelist (allow only develop and version-tagged builds)
branches:
  only:
    - develop
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

# Build Stage Order
stages:
  - OSX Build / Deploy
