parameters:
  - name: extraflags
    default: ''

steps:
  - bash: |
      set -ex
      # -- General
      sudo apt-get update -q
      sudo apt-get install antlr4 gcc-8 ninja-build libopenmpi-dev openmpi-bin openmpi-common python3-setuptools uuid uuid-dev
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      sudo pip3 install wheel
      sudo pip3 install conan
    displayName: 'Install Conan'
  - bash: |
      set -ex
      mkdir build
      cd build
      conan install --remote=conan-center -s compiler.libcxx=libstdc++11 ../
      cmake -G "Ninja" -DPARALLEL:bool=true -DBUILD_ANTLR_RUNTIME:bool=true ${{ parameters.extraflags }} ../
      ninja
    displayName: 'Build'
