parameters:
  - name: extraflags
    default: ''

steps:
  - bash: |
      set -ex
      # -- General
      brew update-reset
      brew install antlr antlr4-cpp-runtime bison ftgl ninja
      # -- Qt
      brew install qt5
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      pip3 install conan
    displayName: 'Install Conan'
  - bash: |
      set -ex
      QTVER=`ls -d /usr/local/Cellar/qt/* | sed "s/.*\(5\.[0-9][0-9]\.[0-9]\)/\1/g"`
      export Qt5_DIR=/usr/local/Cellar/qt/$QTVER/lib/cmake/Qt5
      export Qt5Core_DIR=/usr/local/Cellar/qt/$QTVER/lib/cmake/Qt5Core
      export Qt5Widgets_DIR=/usr/local/Cellar/qt/$QTVER/lib/cmake/Qt5Widgets
      export Qt5PrintSupport_DIR=/usr/local/Cellar/qt/$QTVER/lib/cmake/Qt5PrintSupport
      export Qt5Gui_DIR=/usr/local/Cellar/qt/$QTVER/lib/cmake/Qt5Gui
      Qt5_ROOT=/usr/local/Cellar/qt/${QTVER}
      ANTLR_EXE=`find /usr/local/Cellar/antlr/4.9* -iname antlr`
      echo "Detected ANTLR exe as [$ANTLR_EXE]"
      mkdir build
      cd build
      conan install --remote=conan-center ../
      cmake -G "Ninja" -DGUI:bool=true -DANTLR_EXECUTABLE:string=$ANTLR_EXE ${{ parameters.extraflags }} ../
      ninja
    displayName: 'Build'
