name: AppImage (GUI/Serial)

on:
  push:
    branches:
    - develop
    - master

jobs:
  prepcontinuous:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: contains(github.ref, 'develop')
    steps:
    - uses: actions/checkout@v1
    - name: Create Continuous Release
      run: |
        SHORTHASH=`git rev-parse --short HEAD`
        DATE=`date`
        ./ci/scripts/update-release -r ${{ github.repository }} -t continuous -n "Continuous Build (${SHORTHASH})" -b "Continuous release from current \`develop\` branch at ${SHORTHASH}. Built ${DATE}." -p -e -u
  preprelease:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: contains(github.ref, 'master')
    steps:
    - uses: actions/checkout@v1
    - name: Create Versioned Release
      run: |
        DISSOLVE_VERSION=`grep "DISSOLVEVERSION" src/version.h | sed "s/.*\"\(.*\)\"/\1/g"`
        echo "Code version detected as: $DISSOLVE_VERSION"
        ./ci/scripts/update-release -r ${{ github.repository }} -t ${DISSOLVE_VERSION} -n "v${DISSOLVE_VERSION}" -f Recent.md
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisties
      run: |
        sudo apt-get install bison libfreetype6-dev libftgl-dev ninja-build
        sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y
        sudo apt-get update -q
        sudo apt-get install qt512base qt512svg qt512imageformats -y
    - name: Build (CMake/Ninja)
      run: |
        QT_BASE_DIR=/opt/qt512
        export QTDIR=$QT_BASE_DIR
        export PATH=$QT_BASE_DIR/bin:$PATH
        export LD_LIBRARY_PATH=$QT_BASE_DIR/lib/x86_64-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
        mkdir build
        cd build
        cmake -G "Ninja" -DGUI:bool=true ../
        ninja
        cd ../
    - name: Create AppImages
      run: |
        # Set environment vars
        QT_BASE_DIR=/opt/qt512
        export QTDIR=$QT_BASE_DIR
        export PATH=$QT_BASE_DIR/bin:$PATH
        # Prep appimage directories
        ci/scripts/prep-appimage -a Dissolve -v continuous -b build/dissolve
        ci/scripts/prep-appimage -a Dissolve-GUI -v continuous -b build/dissolve-gui
        # Retrieve linuxdeployqt
        echo -e "\nRetrieving linuxdeployqt...\n"
        wget -q https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O linuxdeployqt
        chmod u+x ./linuxdeployqt
        # Run on the targets
        ./linuxdeployqt Dissolve-continuous.AppDir/usr/share/applications/*.desktop -appimage
        ./linuxdeployqt Dissolve-GUI-continuous.AppDir/usr/share/applications/*.desktop -appimage
        # Store artifacts
        mkdir appimages
        mv Dissolve-*-x86_64.AppImage appimages
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: artifacts
        path: appimages/
  updaterelease:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: artifacts
    - name: Update Versioned Release
      run: |
        DISSOLVE_VERSION=`grep "DISSOLVEVERSION" src/version.h | sed "s/.*\"\(.*\)\"/\1/g"`
        echo "Code version detected as: $DISSOLVE_VERSION"
        mv -v artifacts/Dissolve-continuous-x86_64.AppImage Dissolve-${DISSOLVE_VERSION}-x86_64.AppImage
        mv -v artifacts/Dissolve-GUI-continuous-x86_64.AppImage Dissolve-GUI-${DISSOLVE_VERSION}-x86_64.AppImage
        ./ci/scripts/update-release -r ${{ github.repository }} -t ${DISSOLVE_VERSION} -n "v${DISSOLVE_VERSION}" -f Recent.md artifacts/*AppImage
  updatecontinuous:
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: contains(github.ref, 'develop')
    steps:
    - uses: actions/checkout@v1
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: artifacts
    - name: Create Example Data Archive
      uses: actions/download-artifact@v1
      run: |
        DISSOLVE_VERSION=`grep "DISSOLVEVERSION" src/version.h | sed "s/.*\"\(.*\)\"/\1/g"`
        cd ./examples
        ./package-examples -v $DISSOLVE_VERSION
    - name: Update Continuous Release
      run: |
        SHORTHASH=`git rev-parse --short HEAD`
        ./ci/scripts/update-release -r ${{ github.repository }} -t continuous -n "Continuous Build (${SHORTHASH})" -b "Continuous release from current \`develop\` branch at ${SHORTHASH}. Built ${DATE}." -p artifacts/*AppImage examples/*zip examples/*.tar.gz
