name: Pull Request

on:
  pull_request:
    branches:
    - '*'
    paths-ignore:
    - '.github/workflows/benchmark.yml'
    - '.github/workflows/cacheConan.yml'
    - '.github/workflows/cacheNix.yml'
    - '.github/workflows/continuous.yml'
    - '.github/workflows/issues.yml'
    - '.github/workflows/release.yml'
    - '.github/workflows/web**'
    - '.github/ISSUE_TEMPLATE/**'
    - 'web/**'
    - 'README.md'

jobs:

  QC:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: "./.github/workflows/setup"
    - name: Quality Control
      uses: "./.github/workflows/qc"

  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: "./.github/workflows/setup"
      - name: Set Short Hash
        uses: "./.github/workflows/set-short-hash"
      - name: "Build (${{ matrix.os }})"
        uses: "./.github/workflows/build"

  Package:
    needs: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: "./.github/workflows/setup"
      - name: "Package (${{ matrix.os }})"
        uses: "./.github/workflows/package"
