name: System Tests (Parallel)

on:
  push:
    branches:
    - develop
    - master
  pull_request:

jobs:
  systemtests-build-parallel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisties
      run: |
        sudo apt-get install bison ninja-build libopenmpi-dev openmpi-bin openmpi-common
    - name: Build (CMake/Ninja)
      run: |
        mkdir build
        cd build
        cmake -G "Ninja" -DPARALLEL:bool=true ../
        ninja && cp dissolve-mpi ../tests
        cd ../
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: parallel-test-artifacts
        path: tests/
  systemtests-parallel:
    runs-on: ubuntu-latest
    needs: systemtests-build-parallel
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Install Prerequisties
      run: |
        sudo apt-get install openmpi-bin openmpi-common
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: parallel-test-artifacts
    - name: Run Tests
      run: |
        cd parallel-test-artifacts
        chmod u+x ./go ./dissolve-mpi
        ./go -a -p ./dissolve-mpi
