name: System Tests (Serial)

on:
  push:
    branches:
    - NOdevelop
    - NOmaster
      #pull_request:

jobs:
  systemtests-build-serial:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisties
      run: |
        sudo apt-get install bison ninja-build
    - name: Build (CMake/Ninja)
      run: |
        mkdir build
        cd build
        cmake -G "Ninja" ../
        ninja && cp dissolve ../tests
        cd ../
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: serial-test-artifacts
        path: tests/
  systemtests-serial:
    runs-on: ubuntu-latest
    needs: systemtests-build-serial
    strategy:
      matrix:
        test: [atomshake, broadening, calculate_avgmol, calculate_cn, calculate_dangle, calculate_rdf, calculate_sdf, correlations, energyforce1, epsr, exchangeable, pbctorsion, rdfmethod]
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: serial-test-artifacts
    - name: Run Tests
      run: |
        cd serial-test-artifacts
        chmod u+x ./go ./dissolve
        ./go -a -s ./dissolve ${{ matrix.test }}
