baseURL = "https://www.projectdissolve.com/"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

title = "Dissolve"
theme = ["github.com/google/docsy", "github.com/google/docsy/dependencies"]

enableGitInfo = true
enableInlineShortcodes = true
relativeURLs = true

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

## Menu Definition
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Packages"
    url = "packages/"
    weight = 2

  [[menu.main]]
    name = "User Guide"
    url = "https://docs.projectdissolve.com/"
    weight = 3

  [[menu.main]]
    name = "Examples"
    url = "https://docs.projectdissolve.com/examples/"
    weight = 4

# General Parameters
[params]
copyright = "Team Dissolve and contributors. Built using Hugo/Docsy."
releaseVersion = "1.4.1"
releaseDate = "17th January 2024"
devVersion = "1.4.0"
github_repo = "https://github.com/disorderedmaterials/dissolve"
github_subdir = "web"
github_branch = "develop"

# User interface configuration
[params.ui]
# Set to true to disable breadcrumb navigation.
breadcrumb_disable = true
# Enable to show the side bar menu in its compact state
sidebar_menu_compact = true
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true

# Link Definitions
[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
 [[params.links.developer]]
    name = "GitHub"
    url = "https://github.com/disorderedmaterials/dissolve"
    icon = "fab fa-github"
        desc = "Development takes place here!"

# Modules
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
